# default values
all:
  .settings:
    categories:
      'Manage User'   : '@users'
      'Manage Role'   : '@role'
      'Manage Category'    : '@questioncategory'
      'Manage Question' : '@question'