default:
  http_metas:
    content-type: text/html; charset=gb2312

  metas:
    title:        My Solution
    robots:       index, follow
    description:  Solution project
    keywords:     Solution, project

  stylesheets:    [main]

  javascripts:    [ ]

  has_layout:     on
  layout:         layout

  slots:          {}

  use_default_slots: on
