generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Question
    theme:            default
    fields:
      question: { name: 标题 }
      question_title: { name: 标题 }
      category: { name: 所属分类 }
      question_category_list: { name: 所属分类 }
      question_category: { name: 所属分类 }
      solution_count: { name: 已有方案 }
      active: { name: 激活 }
      active_list: { name: 激活 }
    list:
      tab_bar: list_tab
      display: [_question_title, _question_category_list, _solution_count, _active_list ]
      max_per_page:   5
      title:          问题列表
      sort: [created_at, desc]
      object_actions:
        _edit:        -
        _delete:      -
        addsolution:   { name: 发表解决方案, action: addSolution, icon: add.png }
    edit:
      tab_bar: edit_tab
      title:          编辑问题%%question%%
      display:     [question, _question_category, _active ]
      fields:
          question: { type: textarea_tag, params: rich=true tinymce_options=width:100% tinymce_options=height:350 size=120 }
    