my_solution:
  so_users:
    _attributes: { phpName: Users }
    id:
    user_name:   varchar(60)
    user_pwd:	varchar(50)
    gender:	varchar(8)
    addrees:	varchar(150)
    phone:	varchar(80)
    email:	varchar(80)
    photo:	varchar(80)
    role_id:	{ type: integer, size: 8 }
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_role:
    _attributes: { phpName: Role }
    id:
    role_name:   varchar(60)
    role_lable:	varchar(50)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_question_category:
    _attributes: { phpName: QuestionCategory }
    id:
    category_name:   varchar(60)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_question:
    _attributes: { phpName: Question }
    id:
    question:   longvarchar
    category:	varchar(10)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_solution:
    _attributes: { phpName: Solution }
    id:
    question_id:   { type: INTEGER, size: 11, defaultValue: 1 }
    solution:	longvarchar
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
 