my_solution:
  so_users:
    _attributes: { phpName: Users }
    id:
    user_name:   varchar(60)
    user_pwd:	varchar(50)
    gender:	varchar(8)
    addrees:	varchar(150)
    phone:	varchar(80)
    email:	varchar(80)
    photo:	varchar(80)
    role_id:	{ type: integer, size: 8 }
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_role:
    _attributes: { phpName: Role }
    id:
    role_name:   varchar(60)
    role_lable:	varchar(50)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_question_category:
    _attributes: { phpName: QuestionCategory }
    id:
    category_name:   varchar(60)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_question:
    _attributes: { phpName: Question }
    id:
    question:   longvarchar
    category:	{ type: INTEGER, size: 5, defaultValue: 1 }
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_solution:
    _attributes: { phpName: Solution }
    id:
    question_id:   { type: INTEGER, size: 5, defaultValue: 1 }
    solution:	longvarchar
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_finance_category:
    _attributes: { phpName: FinanceCategory }
    id:
    category_name:   varchar(60)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_finance:
    _attributes: { phpName: Finance }
    id:
    category:  { type: INTEGER, size: 5, defaultValue: 1 }
    create_date: DATE
    amount: { type: tinyint, size: 4, defaultValue: 1 }
    debit: { type: tinyint, size: 2, defaultValue: 1 }
    money:  { type: DECIMAL, size: 10, scale: 2 }
    memo: longvarchar
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_contact_category:
    _attributes: { phpName: ContactCategory }
    id:
    category_name:   varchar(60)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_contact:
    _attributes: { phpName: Contact }
    id:
    category:  { type: INTEGER, size: 5, defaultValue: 1 }
    company_id:  { type: INTEGER, size: 5, defaultValue: 1 }
    name: varchar(50)
    gender: varchar(2)
    birthday: DATE
    addrees:	varchar(150)
    office_phone:	varchar(80)
    phone:	varchar(80)
    fax:	varchar(80)
    mobile:	varchar(80)
    email:	varchar(80)
    photo:	varchar(60)
    homepage:	varchar(90)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_company:
    _attributes: { phpName: Company }
    id:
    name: varchar(50)
    addrees:	varchar(150)
    phone:	varchar(80)
    fax:	varchar(80)
    email:	varchar(80)
    photo:	varchar(60)
    homepage:	varchar(90)
    employee: { type: INTEGER, size: 5 }
    bankroll: { type: DECIMAL, size: 10, scale: 2 }
    link_man: varchar(50)
    incorporator: varchar(50)
    industry: varchar(50)
    products: longvarchar
    memo: longvarchar
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_product_category:
    _attributes: { phpName: ProductCategory }
    id:
    category_name:   varchar(60)
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
  so_product:
    _attributes: { phpName: Product }
    id:
    category:  { type: INTEGER, size: 5, defaultValue: 1 }
    company_id:  { type: INTEGER, size: 5, defaultValue: 1 }
    name: varchar(60)
    price:  { type: DECIMAL, size: 10, scale: 2 }
    photo:	varchar(60)
    memo: longvarchar
    active: { type: tinyint, size: 2, defaultValue: 1 }
    add_ip:	varchar(24)
    created_at:
 