generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Users
    theme:            default
    list:
      max_per_page:   5
      title:          List of Users Test
      object_actions:
        _edit:        -
        _delete:      -
    edit:
      title:          Edit users